commit:
  includes:
    - ruby-standard
    - git
    - base

  externals:
    - repo: "metabahn/commit-templates"
      private: true

git:
  ignore:
    - "tmp"
    - "*.bundle"
    - "*.gem"
    - "Gemfile.lock"
    - ".ruby-version"
